### ISSUE TITLE
Training each round from scratch?

### ISSUE THREAD

**Issue by Ab-34** [ChenhongyiYang/PPAL#15]
Thank you very much for your code.

I had a slight clarification. In each round, you are adding the new data to the old, saving as a json file and training from scratch (with model initialized to resnet checkpoints), right?

As in the training command for each round, the resume-checkpoint and the auto-resume have not been passed as arguments.

**Comment by ChenhongyiYang** [comment]
yes, the models are training from scratch in each round.
